name: Build and test Rust code

on:
    push:
        branches: [trunk]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: cachix/install-nix-action@v26
            - uses: cachix/cachix-action@v14
              with:
                name: devenv
            - name: Install devenv.sh
              run: nix profile install nixpkgs#devenv
            - name: Build and test
              run: devenv test